In [31]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [32]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-13 20:57:35][INFO] 2026-01-13 20:57:35.388976


In [33]:
%autoreload 2
from src import eliminacion_gaussiana


In [34]:
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

In [35]:
import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A

In [36]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[1, 3, 4], [2, 1, 3], [4, 2, 1]]
[01-13 20:57:35][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:57:35][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 20:57:35][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [37]:
# Poner matriz identidad a la derecha
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[1., 3., 4., 1., 0., 0.],
       [2., 1., 3., 0., 1., 0.],
       [4., 2., 1., 0., 0., 1.]])

In [38]:
np.vstack((A, np.eye(n)))

array([[1., 3., 4.],
       [2., 1., 3.],
       [4., 2., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:57:36][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 20:57:36][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 20:57:36][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [-0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [-0. , -0. ,  1. , -0. ,  0.4, -0.2]])

In [40]:
_m_inv[:, n:]

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

# Comprobando respuesta

In [41]:
np.linalg.inv(np.array(A))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

## Matriz A_2

In [42]:
A_2 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

In [43]:
from pprint import pprint

pprint(A_2)
gauss_jordan(A_2)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]
[01-13 20:57:36][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 20:57:36][INFO] 
[[ 1.  0. -5.]
 [ 0.  1.  4.]
 [ 0.  0.  1.]]
[01-13 20:57:36][INFO] 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
n = len(A_2)
A_aug = np.hstack((A_2, np.eye(n)))
A_aug

array([[1., 2., 3., 1., 0., 0.],
       [0., 1., 4., 0., 1., 0.],
       [5., 6., 0., 0., 0., 1.]])

In [45]:
np.vstack((A_2, np.eye(n)))

array([[1., 2., 3.],
       [0., 1., 4.],
       [5., 6., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
_m_inv = gauss_jordan(A_aug)
_m_inv

[01-13 20:57:36][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 20:57:36][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 20:57:37][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


array([[  1.,   0.,   0., -24.,  18.,   5.],
       [  0.,   1.,   0.,  20., -15.,  -4.],
       [  0.,   0.,   1.,  -5.,   4.,   1.]])

In [47]:
_m_inv[:, n:]

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [48]:
np.linalg.inv(np.array(A_2))

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

## Matriz A_3

In [52]:
A_3 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

from pprint import pprint

pprint(A_3)
gauss_jordan(A_3)

n = len(A_3)
A_aug = np.hstack((A_3, np.eye(n)))
A_aug

np.vstack((A_3, np.eye(n)))

_m_inv = gauss_jordan(A_aug)
_m_inv

_m_inv[:, n:]

[[4, 2, 1], [2, 1, 3], [1, 3, 4]]
[01-13 21:00:11][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:00:11][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:00:11][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[01-13 21:00:11][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 21:00:11][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 21:00:11][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]


array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

In [53]:
np.linalg.inv(np.array(A_3))

array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4,  0. ]])

## Matriz A_4

In [ ]:
A_4 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

from pprint import pprint

pprint(A_4)
gauss_jordan(A_4)

n = len(A_3)
A_aug = np.hstack((A_4, np.eye(n)))
A_aug

np.vstack((A_4, np.eye(n)))

_m_inv = gauss_jordan(A_aug)
_m_inv

_m_inv[:, n:]